apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: exam-farrukh
  labels:
    project: practice
    author: farrukh
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
